return {
  "onsails/lspkind-nvim",
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-nvim-lua",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-buffer",
  { import = "plugins.conform" },
  { import = "plugins.dressing" },
  { import = "plugins.lsp" },
  { import = "plugins.treesitter" },
  { import = "plugins.lint" },
  { import = "plugins.autotag" },
  { import = "plugins.better-escape" },
  { import = "plugins.diffview" },
  { import = "plugins.leap" },
  { import = "plugins.bqf" },
  { import = "plugins.trouble" },
  { import = "plugins.lazygit" },
  { import = "plugins.todo-comments" },
  { import = "plugins.supermaven" },
  { import = "plugins.cmp" },
  { import = "plugins.flog" },
  { import = "plugins.tailwind-tool" },
  { import = "plugins.hover" },
  { import = "plugins.markdown" },
  {import = "plugins.ufo"},
  {import = "plugins.noice"}
}
